# Generated by Django 3.2.5 on 2021-08-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tender_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='buyer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='participant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
